-- =============================================================================
--  MCP Bridge Platform - 控制面初始表结构（Postgres 14+）
--  表结构与 JPA 实体一一对应；Hibernate ddl-auto=validate 会在启动时校验一致性。
--  约定：所有 jsonb 列存放模型/诊断/快照；密钥类列一律以 _enc 结尾（密文）。
-- =============================================================================

-- ---------- 组织与账号（MGM-01/02/03） ----------
CREATE TABLE department
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64)  NOT NULL,
    parent_id   BIGINT,
    description VARCHAR(255),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX idx_department_parent ON department (parent_id);

CREATE TABLE role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64) NOT NULL UNIQUE,
    name        VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    builtin     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);

CREATE TABLE role_permission
(
    role_id    BIGINT      NOT NULL REFERENCES role (id) ON DELETE CASCADE,
    permission VARCHAR(64) NOT NULL,
    PRIMARY KEY (role_id, permission)
);

-- user 是 Postgres 保留字，表名用 platform_user
CREATE TABLE platform_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(64),
    email         VARCHAR(128),
    dept_id       BIGINT       NOT NULL REFERENCES department (id),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ
);
CREATE INDEX idx_user_dept ON platform_user (dept_id);

CREATE TABLE platform_user_role
(
    user_id BIGINT NOT NULL REFERENCES platform_user (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES role (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- ---------- 注册与解析（REG-01/02/03） ----------
-- raw_doc 为原文只读存档（BR-2/N3）：应用层禁止更新，sha256 做完整性双保险
CREATE TABLE api_registration
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id         BIGINT       NOT NULL REFERENCES department (id),
    name            VARCHAR(128) NOT NULL,
    doc_source      VARCHAR(16)  NOT NULL,
    source_ref      VARCHAR(512),
    swagger_version VARCHAR(16),
    raw_doc         JSONB,
    raw_doc_sha256  VARCHAR(64),
    doc_version     INT          NOT NULL DEFAULT 1,
    status          VARCHAR(16)  NOT NULL,
    diagnostics     JSONB,
    operation_count INT,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ
);
CREATE INDEX idx_registration_dept ON api_registration (dept_id);
CREATE INDEX idx_registration_status ON api_registration (status);

-- ---------- MCP Server / Tool（SVR-01/02/04） ----------
CREATE TABLE mcp_server
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id          BIGINT       NOT NULL REFERENCES department (id),
    registration_id  BIGINT       NOT NULL UNIQUE REFERENCES api_registration (id),
    name             VARCHAR(128) NOT NULL,
    path_segment     VARCHAR(64)  NOT NULL,
    title            VARCHAR(128),
    description      VARCHAR(2000),
    version          VARCHAR(32),
    protocol_version VARCHAR(16)  NOT NULL,
    base_model       JSONB,
    overlay          JSONB,
    overlay_version  INT          NOT NULL DEFAULT 0,
    upstream         JSONB,
    auth_d           JSONB,
    list_ttl_ms      INT          NOT NULL DEFAULT 30000,
    status           VARCHAR(24)  NOT NULL,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ
);
CREATE INDEX idx_server_dept ON mcp_server (dept_id);
-- PATH 末段唯一性是「集群内」语义（BR-3），跨表判定在服务层完成，此处仅建索引
CREATE INDEX idx_server_path_segment ON mcp_server (path_segment);

CREATE TABLE mcp_tool
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id             BIGINT       NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
    anchor                VARCHAR(512) NOT NULL,
    method                VARCHAR(16)  NOT NULL,
    path                  VARCHAR(512) NOT NULL,
    base_name             VARCHAR(64)  NOT NULL,
    base_summary          VARCHAR(512),
    base_description      VARCHAR(4000),
    base_input_schema     JSONB,
    parameter_in          JSONB,
    request_body_required BOOLEAN      NOT NULL DEFAULT FALSE,
    idempotent            BOOLEAN      NOT NULL DEFAULT FALSE,
    streaming             BOOLEAN      NOT NULL DEFAULT FALSE,
    stream_format         VARCHAR(16),
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    overlay               JSONB,
    overlay_status        VARCHAR(16)  NOT NULL DEFAULT 'NONE',
    sort_order            INT          NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ,
    CONSTRAINT uk_tool_server_anchor UNIQUE (server_id, anchor)
);
CREATE INDEX idx_tool_server ON mcp_tool (server_id);

-- ---------- 上行鉴权 Auth-B（SVR-03 / SEC-01） ----------
-- tool_id = 0 表示 Server 级配置，非 0 为 tool 级覆盖（BR-4，P1）
CREATE TABLE auth_config
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id         BIGINT      NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
    tool_id           BIGINT      NOT NULL DEFAULT 0,
    type              VARCHAR(32) NOT NULL,
    in_location       VARCHAR(16),
    name              VARCHAR(64),
    scheme            VARCHAR(32),
    username          VARCHAR(128),
    secret_enc        VARCHAR(2048),
    password_enc      VARCHAR(2048),
    token_url         VARCHAR(512),
    client_id         VARCHAR(128),
    client_secret_enc VARCHAR(2048),
    scope             VARCHAR(256),
    header_template   VARCHAR(2048),
    extra_headers     JSONB,
    masked_preview    VARCHAR(255),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ,
    CONSTRAINT uk_auth_config_server_tool UNIQUE (server_id, tool_id)
);

-- ---------- 集群与节点（PUB-01/02） ----------
CREATE TABLE executor_cluster
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(64)  NOT NULL UNIQUE,
    type            VARCHAR(16)  NOT NULL,
    entrypoint      VARCHAR(255) NOT NULL,
    path_prefix     VARCHAR(32)  NOT NULL DEFAULT 'mcp',
    owner_dept_id   BIGINT,
    description     VARCHAR(255),
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    scopes          JSONB,
    node_token_hash VARCHAR(64),
    revision        BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ
);

CREATE TABLE cluster_grant
(
    cluster_id BIGINT NOT NULL REFERENCES executor_cluster (id) ON DELETE CASCADE,
    dept_id    BIGINT NOT NULL,
    PRIMARY KEY (cluster_id, dept_id)
);

CREATE TABLE executor_node
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_id       BIGINT       NOT NULL REFERENCES executor_cluster (id) ON DELETE CASCADE,
    node_key         VARCHAR(128) NOT NULL,
    host             VARCHAR(128),
    port             INT,
    version          VARCHAR(32),
    protocol_version VARCHAR(16),
    status           VARCHAR(16)  NOT NULL DEFAULT 'OFFLINE',
    last_heartbeat_at TIMESTAMPTZ,
    load_info        JSONB,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT uk_node_cluster_key UNIQUE (cluster_id, node_key)
);
CREATE INDEX idx_node_status_heartbeat ON executor_node (status, last_heartbeat_at);

-- ---------- 发布（PUB-03/04） ----------
-- snapshot 固化发布当时的生效模型，回滚只需把 is_current 指回历史行
CREATE TABLE publish_binding
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id      BIGINT      NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
    cluster_id     BIGINT      NOT NULL REFERENCES executor_cluster (id) ON DELETE CASCADE,
    version        BIGINT      NOT NULL,
    state          VARCHAR(16) NOT NULL,
    is_current     BOOLEAN     NOT NULL DEFAULT FALSE,
    snapshot       JSONB,
    published_by   BIGINT,
    published_at   TIMESTAMPTZ,
    offlined_at    TIMESTAMPTZ,
    failure_reason VARCHAR(1024),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ
);
CREATE INDEX idx_binding_current ON publish_binding (cluster_id, is_current);
CREATE INDEX idx_binding_server ON publish_binding (server_id, cluster_id, version DESC);

-- ---------- 审计（MGM-05，append-only） ----------
CREATE TABLE audit_log
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,
    actor_name  VARCHAR(64),
    action      VARCHAR(64) NOT NULL,
    target_type VARCHAR(32),
    target_id   VARCHAR(64),
    dept_id     BIGINT,
    detail      JSONB,
    trace_id    VARCHAR(64),
    client_ip   VARCHAR(64),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_created ON audit_log (created_at DESC);
CREATE INDEX idx_audit_target ON audit_log (target_type, target_id);
CREATE INDEX idx_audit_dept ON audit_log (dept_id);