-- V2: 多 REST 服务支持 —— 1 MCP Server = N Upstream
-- 设计见 docs/spike/Multi-Upstream-Server-Design.md
-- 平台未上线，不做兼容迁移，破坏性变更。

-- 1. 上游服务表：一个 Server 挂多个 REST 服务，每个独立 upstream / Auth-B / 熔断
CREATE TABLE server_upstream
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id       BIGINT       NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
    service_id      VARCHAR(64)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    base_urls       JSONB        NOT NULL,
    lb_strategy     VARCHAR(16)  NOT NULL DEFAULT 'ROUND_ROBIN',
    weights         JSONB,
    connect_timeout BIGINT       NOT NULL DEFAULT 3000,
    read_timeout   BIGINT       NOT NULL DEFAULT 30000,
    retries         INT          NOT NULL DEFAULT 1,
    retry_on_status JSONB,
    circuit_breaker JSONB,
    auth_b          JSONB,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ,
    CONSTRAINT uk_server_upstream_service UNIQUE (server_id, service_id)
);
CREATE INDEX idx_server_upstream_server ON server_upstream (server_id);

-- 2. mcp_server.registration_id 去 UNIQUE（改为 N:1，一个 Server 可绑多份 registration）
ALTER TABLE mcp_server DROP CONSTRAINT IF EXISTS mcp_server_registration_id_key;

-- 3. mcp_server.upstream 列删除（upstream 下沉到 server_upstream 表）
ALTER TABLE mcp_server DROP COLUMN IF EXISTS upstream;

-- 4. mcp_tool 新增 upstream_ref 列（指向 server_upstream.service_id）
ALTER TABLE mcp_tool ADD COLUMN upstream_ref VARCHAR(64);

-- 5. tool 唯一约束扩展：跨服务同名 anchor 允许，按 (server_id, upstream_ref, anchor) 唯一
ALTER TABLE mcp_tool DROP CONSTRAINT IF EXISTS uk_tool_server_anchor;
ALTER TABLE mcp_tool ADD CONSTRAINT uk_tool_server_upstream_anchor UNIQUE (server_id, upstream_ref, anchor);
