-- V4: 跨部门访问申请 —— server_access（按部门申请、按部门授权，只读）
-- 设计见 docs/spike/CrossDept-Server-Access-Design.md
-- 状态机：PENDING → APPROVED / REJECTED；APPROVED → REVOKED（所属部门回收）；REJECTED → PENDING（带新理由重提）

CREATE TABLE server_access
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id    BIGINT       NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
    dept_id      BIGINT       NOT NULL REFERENCES department (id),
    status       VARCHAR(16)  NOT NULL,
    reason       VARCHAR(500),
    requested_by BIGINT       NOT NULL,
    requested_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    reviewed_by  BIGINT,
    reviewed_at  TIMESTAMPTZ,
    review_note  VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT uk_server_access UNIQUE (server_id, dept_id)
);
CREATE INDEX idx_server_access_dept ON server_access (dept_id);
CREATE INDEX idx_server_access_status ON server_access (status);
CREATE INDEX idx_server_access_server ON server_access (server_id);
