-- V7: Resource / Prompt 手动目录（SVR-05 / SVR-06）
--
-- 背景：Executor 运行时早就实现了 resources/list·read、prompts/list·get，
-- 但控制面一直没有模型/组装/UI，于是快照里这两个数组恒为空——「实现完整的一侧 + 完全空白的一侧」。
-- 本迁移补上控制面的存储。
--
-- 为什么不从 Swagger 推导：OpenAPI 里没有 resource / prompt 的对应概念，
-- 只能手动配置。这一条决定了它必然是 P1 而不是注册解析的延伸。

-- 1. MCP Resource：静态内容 或 映射到一个 tool（resources/read 时透传调用），二选一
CREATE TABLE mcp_resource
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id      BIGINT       NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
    uri            VARCHAR(512) NOT NULL,
    name           VARCHAR(128),
    description    VARCHAR(2000),
    mime_type      VARCHAR(128),
    -- 静态内容与 tool_id 互斥；应用层校验，DB 层不强制（历史导入/人工修库时留一点余地）
    static_content TEXT,
    -- tool 被删时置空而不是连坐删除：资源本身还在，只是失去了数据来源，运维能看出来并修
    tool_id        BIGINT       REFERENCES mcp_tool (id) ON DELETE SET NULL,
    ttl_ms         INT,
    sort_order     INT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ,
    CONSTRAINT uk_resource_server_uri UNIQUE (server_id, uri)
);
CREATE INDEX idx_resource_server ON mcp_resource (server_id);

-- 2. MCP Prompt：模板文本 + 参数声明（模板占位符规则见 common 的 PromptTemplate）
CREATE TABLE mcp_prompt
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id   BIGINT       NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
    name        VARCHAR(128) NOT NULL,
    title       VARCHAR(128),
    description VARCHAR(2000),
    template    TEXT,
    arguments   JSONB,
    ttl_ms      INT,
    sort_order  INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT uk_prompt_server_name UNIQUE (server_id, name)
);
CREATE INDEX idx_prompt_server ON mcp_prompt (server_id);
